### ISSUE TITLE
Refactor <HistoricalFigures />

### ISSUE THREAD

**Issue by bbenefield89** [bbenefield89/LegendsViewerBrowser-Client#1]
The <HistoricalFigures /> component should closely follow the LegendsViewer layout.

Open to changes or ideas.

# Tasks
- [ ] Name
- [ ] Gender/caste
- [ ] Unit "Type"
- [ ] List "Related Entities" with a link to that entity
- [ ] List "Related Sites" with a link to that site
- [ ] List "Kills" with link to each historical figure killed
- [ ] List "Life Events"

# If Sphere/Deity
- [ ] Display "associated spheres"

# Notes
- Look into "Beast Attacks". This may be on figures that are animals/were/vampire and when they attack something.

# Example
![image](https://user-images.githubusercontent.com/29239201/57183735-42ac4980-6e7f-11e9-815f-b84bfee4d1ff.png)
